# Generated by Django 3.1.4 on 2020-12-09 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assign_db', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='img',
        ),
        migrations.AddField(
            model_name='destination',
            name='file_name',
            field=models.FileField(default=0, upload_to='files'),
            preserve_default=False,
        ),
    ]
