# Generated by Django 3.1.4 on 2020-12-11 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assign_db', '0003_auto_20201210_0419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='offer',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='price',
        ),
        migrations.AlterField(
            model_name='destination',
            name='desc',
            field=models.CharField(max_length=100),
        ),
    ]
